### ISSUE TITLE
Bug: Can not download playlist in the playlist tab

### ISSUE THREAD

**Issue by XanderStoffels** [rohankishore/Spotifyte#3]
When I paste a playlist link in the playlist tab, it says I'm in trying to download a playlist in the Songs tab.

![image](https://github.com/rohankishore/Spotifyte/assets/15852653/af7be22a-4c0e-4ace-8a9b-ddd6f72eb7ce)

**Comment by rohankishore** [comment]
Oops. I'll fix it right away and update all the EXEs. Thank you!

**Comment by rohankishore** [comment]
Currently updating the EXEs.
